== Central Service: Source Code Repository

* for source code created or used by ACME Corp only

=== Building the Gogs container image

Please have a look at the `Makefile`, change `REPOSITORY_NAME` according to your needs.

A simple `make push` should do the rest.

```
make push
```

Mind the Gap! There is a build id in the `Makefile` and the `openshift-template.yaml` and in the `Dockerfile`

==== Open Issues

* Put some sane default configuration via ConfigMap

=== Creating Gogs template

An OpenShift template is provided and could be used to instanciate new Gogs
applications. Therefore the template needs to be created on OpenShift: `oc create -f openshift-template.yaml`.
This assumes that you have create a project on OpenShift, for detailed instruction
see Creating a Project[https://docs.openshift.org/latest/dev_guide/projects.html#create-a-project].

=== Creating Gogs application

Deploying Gogs on OpenShift is a simple step of instanciating a new
application on OpenShift. To provide default configurations to Gogs,
a ConfigMap will be used, this is not created by the template. Please create
it beforehand:

```
oc create configmap gogs-default-config --from-file=app.ini=etc-gogs-conf/app.ini
oc new-app gogs
```

=== Remove application from OCP

```
oc scale deploymentconfig gogs-postgresql --replicas=0
oc delete deploymentconfig gogs-postgresql
oc delete service gogs-postgresql
oc scale deploymentconfig gogs --replicas=0
oc delete deploymentconfig gogs
oc delete service gogs
oc delete routes gogs
oc delete pod --all
oc delete imagestream gogs
oc delete configmap gogs-default-config
oc delete serviceaccount gogs
oc delete template gogs
```

Persistent Volumes are not deleted using these commands.
